# Form implementation generated from reading ui file 'Ui_Producto.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Ui_Producto(object):
    def setupUi(self, Ui_Producto):
        Ui_Producto.setObjectName("Ui_Producto")
        Ui_Producto.resize(1047, 616)
        Ui_Producto.setStyleSheet("QWidget{\n"
"background-color:white;\n"
"}\n"
"\n"
"QLabel{\n"
"font-family:\"Sans-serif\";\n"
"font-size:14px;\n"
"padding:5px;\n"
"\n"
"}\n"
"\n"
"QDoubleSpinBox{\n"
"font-family:\"Sans-serif\";\n"
"font-size:14px;\n"
"padding:10px 10px;\n"
"border-radius:10px;\n"
"border:2px solid rgb(228, 232, 235);\n"
"}\n"
"\n"
"QComboBox{\n"
"font-family:\"Sans-serif\";\n"
"font-size:14px;\n"
"padding:10px 10px;\n"
"border-radius:10px;\n"
"border:2px solid rgb(228, 232, 235);\n"
"}\n"
"\n"
"QLineEdit{\n"
"font-family:\"Sans-serif\";\n"
"font-size:14px;\n"
"padding:10px 10px;\n"
"border-radius:10px;\n"
"border:2px solid rgb(228, 232, 235);\n"
"}\n"
"\n"
"QPushButton{\n"
"font-family:\"Sans-serif\";\n"
"background-color: #E4E8EB;\n"
"padding: 10px 10px;\n"
"border-radius: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit:hover{\n"
"border:2px solid black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:2px solid black;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Ui_Producto)
        self.gridLayout.setObjectName("gridLayout")
        self.tbProducto = QtWidgets.QTabWidget(parent=Ui_Producto)
        self.tbProducto.setObjectName("tbProducto")
        self.tbIngresar = QtWidgets.QWidget()
        self.tbIngresar.setObjectName("tbIngresar")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tbIngresar)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 10, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cmbIngredienteIngresar = QtWidgets.QComboBox(parent=self.tbIngresar)
        self.cmbIngredienteIngresar.setObjectName("cmbIngredienteIngresar")
        self.horizontalLayout_2.addWidget(self.cmbIngredienteIngresar)
        self.dsbCantidadIngresar = QtWidgets.QDoubleSpinBox(parent=self.tbIngresar)
        self.dsbCantidadIngresar.setObjectName("dsbCantidadIngresar")
        self.horizontalLayout_2.addWidget(self.dsbCantidadIngresar)
        self.btnAgregarIngredienteIngresar = QtWidgets.QPushButton(parent=self.tbIngresar)
        self.btnAgregarIngredienteIngresar.setObjectName("btnAgregarIngredienteIngresar")
        self.horizontalLayout_2.addWidget(self.btnAgregarIngredienteIngresar)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 9, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnIngresarProducto = QtWidgets.QPushButton(parent=self.tbIngresar)
        self.btnIngresarProducto.setObjectName("btnIngresarProducto")
        self.horizontalLayout.addWidget(self.btnIngresarProducto)
        self.gridLayout_2.addLayout(self.horizontalLayout, 11, 0, 1, 1)
        self.dsbPrecioIngresar = QtWidgets.QDoubleSpinBox(parent=self.tbIngresar)
        self.dsbPrecioIngresar.setObjectName("dsbPrecioIngresar")
        self.gridLayout_2.addWidget(self.dsbPrecioIngresar, 7, 0, 1, 1)
        self.lblNombreIngresar = QtWidgets.QLabel(parent=self.tbIngresar)
        self.lblNombreIngresar.setObjectName("lblNombreIngresar")
        self.gridLayout_2.addWidget(self.lblNombreIngresar, 0, 0, 1, 1)
        self.lblDescripcionIngresar = QtWidgets.QLabel(parent=self.tbIngresar)
        self.lblDescripcionIngresar.setObjectName("lblDescripcionIngresar")
        self.gridLayout_2.addWidget(self.lblDescripcionIngresar, 2, 0, 1, 1)
        self.lblAgregarIngredienteIngresar = QtWidgets.QLabel(parent=self.tbIngresar)
        self.lblAgregarIngredienteIngresar.setObjectName("lblAgregarIngredienteIngresar")
        self.gridLayout_2.addWidget(self.lblAgregarIngredienteIngresar, 8, 0, 1, 1)
        self.lblPrecioIngresar = QtWidgets.QLabel(parent=self.tbIngresar)
        self.lblPrecioIngresar.setObjectName("lblPrecioIngresar")
        self.gridLayout_2.addWidget(self.lblPrecioIngresar, 5, 0, 1, 1)
        self.txtNombreIngresar = QtWidgets.QLineEdit(parent=self.tbIngresar)
        self.txtNombreIngresar.setObjectName("txtNombreIngresar")
        self.gridLayout_2.addWidget(self.txtNombreIngresar, 1, 0, 1, 1)
        self.txtDescripcionIngresar = QtWidgets.QLineEdit(parent=self.tbIngresar)
        self.txtDescripcionIngresar.setObjectName("txtDescripcionIngresar")
        self.gridLayout_2.addWidget(self.txtDescripcionIngresar, 4, 0, 1, 1)
        self.tbProducto.addTab(self.tbIngresar, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lblNombreModificar = QtWidgets.QLabel(parent=self.tab_2)
        self.lblNombreModificar.setObjectName("lblNombreModificar")
        self.gridLayout_3.addWidget(self.lblNombreModificar, 0, 0, 1, 1)
        self.cmbNombreModificar = QtWidgets.QComboBox(parent=self.tab_2)
        self.cmbNombreModificar.setObjectName("cmbNombreModificar")
        self.gridLayout_3.addWidget(self.cmbNombreModificar, 1, 0, 1, 1)
        self.lblAgregarIngredienteModificar = QtWidgets.QLabel(parent=self.tab_2)
        self.lblAgregarIngredienteModificar.setObjectName("lblAgregarIngredienteModificar")
        self.gridLayout_3.addWidget(self.lblAgregarIngredienteModificar, 8, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cmbAgregarIngredienteModificar = QtWidgets.QComboBox(parent=self.tab_2)
        self.cmbAgregarIngredienteModificar.setEnabled(False)
        self.cmbAgregarIngredienteModificar.setObjectName("cmbAgregarIngredienteModificar")
        self.horizontalLayout_4.addWidget(self.cmbAgregarIngredienteModificar)
        self.dsbAgregarPrecioModificar = QtWidgets.QDoubleSpinBox(parent=self.tab_2)
        self.dsbAgregarPrecioModificar.setEnabled(False)
        self.dsbAgregarPrecioModificar.setObjectName("dsbAgregarPrecioModificar")
        self.horizontalLayout_4.addWidget(self.dsbAgregarPrecioModificar)
        self.btnAgregarIngredienteModificar = QtWidgets.QPushButton(parent=self.tab_2)
        self.btnAgregarIngredienteModificar.setEnabled(True)
        self.btnAgregarIngredienteModificar.setObjectName("btnAgregarIngredienteModificar")
        self.horizontalLayout_4.addWidget(self.btnAgregarIngredienteModificar)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 9, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cmbIngredienteModificar = QtWidgets.QComboBox(parent=self.tab_2)
        self.cmbIngredienteModificar.setEnabled(True)
        self.cmbIngredienteModificar.setObjectName("cmbIngredienteModificar")
        self.horizontalLayout_3.addWidget(self.cmbIngredienteModificar)
        self.dsbCantidadModificar = QtWidgets.QDoubleSpinBox(parent=self.tab_2)
        self.dsbCantidadModificar.setEnabled(True)
        self.dsbCantidadModificar.setObjectName("dsbCantidadModificar")
        self.horizontalLayout_3.addWidget(self.dsbCantidadModificar)
        self.btnModificarIngrediente = QtWidgets.QPushButton(parent=self.tab_2)
        self.btnModificarIngrediente.setEnabled(True)
        self.btnModificarIngrediente.setObjectName("btnModificarIngrediente")
        self.horizontalLayout_3.addWidget(self.btnModificarIngrediente)
        self.btnEliminarIngrediente = QtWidgets.QPushButton(parent=self.tab_2)
        self.btnEliminarIngrediente.setEnabled(True)
        self.btnEliminarIngrediente.setObjectName("btnEliminarIngrediente")
        self.horizontalLayout_3.addWidget(self.btnEliminarIngrediente)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 7, 0, 1, 1)
        self.txtDescripcionModificar = QtWidgets.QLineEdit(parent=self.tab_2)
        self.txtDescripcionModificar.setEnabled(True)
        self.txtDescripcionModificar.setObjectName("txtDescripcionModificar")
        self.gridLayout_3.addWidget(self.txtDescripcionModificar, 3, 0, 1, 1)
        self.lblPrecioModificar = QtWidgets.QLabel(parent=self.tab_2)
        self.lblPrecioModificar.setObjectName("lblPrecioModificar")
        self.gridLayout_3.addWidget(self.lblPrecioModificar, 4, 0, 1, 1)
        self.lblDescripcionModificar = QtWidgets.QLabel(parent=self.tab_2)
        self.lblDescripcionModificar.setObjectName("lblDescripcionModificar")
        self.gridLayout_3.addWidget(self.lblDescripcionModificar, 2, 0, 1, 1)
        self.lblIngredienteModificar = QtWidgets.QLabel(parent=self.tab_2)
        self.lblIngredienteModificar.setObjectName("lblIngredienteModificar")
        self.gridLayout_3.addWidget(self.lblIngredienteModificar, 6, 0, 1, 1)
        self.dsbPrecioModificar = QtWidgets.QDoubleSpinBox(parent=self.tab_2)
        self.dsbPrecioModificar.setEnabled(True)
        self.dsbPrecioModificar.setObjectName("dsbPrecioModificar")
        self.gridLayout_3.addWidget(self.dsbPrecioModificar, 5, 0, 1, 1)
        self.btnGuardarCambios = QtWidgets.QPushButton(parent=self.tab_2)
        self.btnGuardarCambios.setObjectName("btnGuardarCambios")
        self.gridLayout_3.addWidget(self.btnGuardarCambios, 10, 0, 1, 1)
        self.tbProducto.addTab(self.tab_2, "")
        self.tbEliminar = QtWidgets.QWidget()
        self.tbEliminar.setObjectName("tbEliminar")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tbEliminar)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lblNombreEliminar = QtWidgets.QLabel(parent=self.tbEliminar)
        self.lblNombreEliminar.setObjectName("lblNombreEliminar")
        self.gridLayout_4.addWidget(self.lblNombreEliminar, 0, 0, 1, 1)
        self.cmbNombreEliminar = QtWidgets.QComboBox(parent=self.tbEliminar)
        self.cmbNombreEliminar.setObjectName("cmbNombreEliminar")
        self.gridLayout_4.addWidget(self.cmbNombreEliminar, 1, 0, 1, 1)
        self.btnEliminarProducto = QtWidgets.QPushButton(parent=self.tbEliminar)
        self.btnEliminarProducto.setObjectName("btnEliminarProducto")
        self.gridLayout_4.addWidget(self.btnEliminarProducto, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 2, 0, 1, 1)
        self.tbProducto.addTab(self.tbEliminar, "")
        self.tbListar = QtWidgets.QWidget()
        self.tbListar.setObjectName("tbListar")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tbListar)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tbProductos = QtWidgets.QTableWidget(parent=self.tbListar)
        self.tbProductos.setObjectName("tbProductos")
        self.tbProductos.setColumnCount(0)
        self.tbProductos.setRowCount(0)
        self.gridLayout_5.addWidget(self.tbProductos, 0, 0, 1, 1)
        self.tbProducto.addTab(self.tbListar, "")
        self.gridLayout.addWidget(self.tbProducto, 0, 0, 1, 1)

        self.retranslateUi(Ui_Producto)
        self.tbProducto.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Ui_Producto)

    def retranslateUi(self, Ui_Producto):
        _translate = QtCore.QCoreApplication.translate
        Ui_Producto.setWindowTitle(_translate("Ui_Producto", "Producto"))
        self.btnAgregarIngredienteIngresar.setText(_translate("Ui_Producto", "Agregar ingrediente"))
        self.btnIngresarProducto.setText(_translate("Ui_Producto", "Ingresar producto"))
        self.lblNombreIngresar.setText(_translate("Ui_Producto", "Nombre"))
        self.lblDescripcionIngresar.setText(_translate("Ui_Producto", "Descripción"))
        self.lblAgregarIngredienteIngresar.setText(_translate("Ui_Producto", "Agregar ingrediente y cantidad"))
        self.lblPrecioIngresar.setText(_translate("Ui_Producto", "Precio"))
        self.txtNombreIngresar.setPlaceholderText(_translate("Ui_Producto", "Ingrese nombre del producto"))
        self.txtDescripcionIngresar.setPlaceholderText(_translate("Ui_Producto", "Ingrese breve descripción del producto"))
        self.tbProducto.setTabText(self.tbProducto.indexOf(self.tbIngresar), _translate("Ui_Producto", "Ingresar"))
        self.lblNombreModificar.setText(_translate("Ui_Producto", "Nombre"))
        self.lblAgregarIngredienteModificar.setText(_translate("Ui_Producto", "Agregar ingrediente y cantidad"))
        self.btnAgregarIngredienteModificar.setText(_translate("Ui_Producto", "Agregar ingrediente"))
        self.btnModificarIngrediente.setText(_translate("Ui_Producto", "Modificar ingrediente"))
        self.btnEliminarIngrediente.setText(_translate("Ui_Producto", "Eliminar ingrediente"))
        self.lblPrecioModificar.setText(_translate("Ui_Producto", "Precio"))
        self.lblDescripcionModificar.setText(_translate("Ui_Producto", "Descripción"))
        self.lblIngredienteModificar.setText(_translate("Ui_Producto", "Ingredientes y cantidad"))
        self.btnGuardarCambios.setText(_translate("Ui_Producto", "Guardar cambios"))
        self.tbProducto.setTabText(self.tbProducto.indexOf(self.tab_2), _translate("Ui_Producto", "Modificar"))
        self.lblNombreEliminar.setText(_translate("Ui_Producto", "Nombre"))
        self.btnEliminarProducto.setText(_translate("Ui_Producto", "Eliminar producto"))
        self.tbProducto.setTabText(self.tbProducto.indexOf(self.tbEliminar), _translate("Ui_Producto", "Eliminar"))
        self.tbProducto.setTabText(self.tbProducto.indexOf(self.tbListar), _translate("Ui_Producto", "Listar"))
