# Form implementation generated from reading ui file 'Ui_AcercaDe.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AcercaDe(object):
    def setupUi(self, Ui_AcercaDe):
        Ui_AcercaDe.setObjectName("Ui_AcercaDe")
        Ui_AcercaDe.resize(1280, 600)
        Ui_AcercaDe.setMinimumSize(QtCore.QSize(800, 600))
        Ui_AcercaDe.setMaximumSize(QtCore.QSize(1366, 768))
        Ui_AcercaDe.setStyleSheet("QWidget{\n"
"background-color:white;\n"
"}\n"
"\n"
"QLabel{\n"
"font-family:\"Sans-serif\";\n"
"font-size:14px;\n"
"padding:5px;\n"
"\n"
"}\n"
"\n"
"QLineEdit{\n"
"font-family:\"Sans-serif\";\n"
"font-size:14px;\n"
"padding:10px 10px;\n"
"border-radius:10px;\n"
"margin-left:10px;\n"
"margin-right: 10px;\n"
"border:2px solid rgb(228, 232, 235);\n"
"}\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(Ui_AcercaDe)
        self.gridLayout.setObjectName("gridLayout")
        self.lblInstitutoDev = QtWidgets.QLabel(parent=Ui_AcercaDe)
        self.lblInstitutoDev.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblInstitutoDev.setObjectName("lblInstitutoDev")
        self.gridLayout.addWidget(self.lblInstitutoDev, 3, 0, 1, 1)
        self.lblNombreDev = QtWidgets.QLabel(parent=Ui_AcercaDe)
        self.lblNombreDev.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblNombreDev.setObjectName("lblNombreDev")
        self.gridLayout.addWidget(self.lblNombreDev, 1, 0, 1, 1)
        self.lblEmailDev = QtWidgets.QLabel(parent=Ui_AcercaDe)
        self.lblEmailDev.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblEmailDev.setObjectName("lblEmailDev")
        self.gridLayout.addWidget(self.lblEmailDev, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=Ui_AcercaDe)
        self.label.setMinimumSize(QtCore.QSize(400, 400))
        self.label.setMaximumSize(QtCore.QSize(400, 400))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("./Vistas/user.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(Ui_AcercaDe)
        QtCore.QMetaObject.connectSlotsByName(Ui_AcercaDe)

    def retranslateUi(self, Ui_AcercaDe):
        _translate = QtCore.QCoreApplication.translate
        Ui_AcercaDe.setWindowTitle(_translate("Ui_AcercaDe", "Acerca de"))
        self.lblInstitutoDev.setText(_translate("Ui_AcercaDe", "Universidad de Cuenca"))
        self.lblNombreDev.setText(_translate("Ui_AcercaDe", "Fabián Ledesma"))
        self.lblEmailDev.setText(_translate("Ui_AcercaDe", "andres.ledesma@ucuenca.edu.ec"))
