# Form implementation generated from reading ui file 'Ui_GestionEncargado.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GestionEncargado(object):
    def setupUi(self, Ui_GestionEncargado):
        Ui_GestionEncargado.setObjectName("Ui_GestionEncargado")
        Ui_GestionEncargado.resize(1280, 600)
        Ui_GestionEncargado.setMinimumSize(QtCore.QSize(800, 600))
        Ui_GestionEncargado.setMaximumSize(QtCore.QSize(1366, 768))
        Ui_GestionEncargado.setStyleSheet("QWidget{\n"
"background-color:white;\n"
"}\n"
"\n"
"QLabel{\n"
"font-family:\"Sans-serif\";\n"
"font-size:14px;\n"
"padding:5px;\n"
"\n"
"}\n"
"\n"
"QLineEdit{\n"
"font-family:\"Sans-serif\";\n"
"font-size:14px;\n"
"padding:10px 10px;\n"
"border-radius:10px;\n"
"margin-left:10px;\n"
"margin-right: 10px;\n"
"border:2px solid rgb(228, 232, 235);\n"
"}\n"
"\n"
"QPushButton{\n"
"font-family:\"Sans-serif\";\n"
"background-color: #E4E8EB;\n"
"padding: 10px 10px;\n"
"border-radius: 10px;\n"
"margin-left:10px;\n"
"margin-right:10px;\n"
"}\n"
"\n"
"\n"
"QLineEdit:hover{\n"
"border:2px solid black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:2px solid black;\n"
"}\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(Ui_GestionEncargado)
        self.gridLayout.setObjectName("gridLayout")
        self.tbEncargado = QtWidgets.QTabWidget(parent=Ui_GestionEncargado)
        self.tbEncargado.setObjectName("tbEncargado")
        self.tbIngresar = QtWidgets.QWidget()
        self.tbIngresar.setObjectName("tbIngresar")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tbIngresar)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblClaveIngresar = QtWidgets.QLabel(parent=self.tbIngresar)
        self.lblClaveIngresar.setObjectName("lblClaveIngresar")
        self.gridLayout_2.addWidget(self.lblClaveIngresar, 6, 0, 1, 1)
        self.txtClaveIngresar = QtWidgets.QLineEdit(parent=self.tbIngresar)
        self.txtClaveIngresar.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtClaveIngresar.setObjectName("txtClaveIngresar")
        self.gridLayout_2.addWidget(self.txtClaveIngresar, 7, 0, 1, 1)
        self.cbxMostrarClaveIngresar = QtWidgets.QCheckBox(parent=self.tbIngresar)
        self.cbxMostrarClaveIngresar.setObjectName("cbxMostrarClaveIngresar")
        self.gridLayout_2.addWidget(self.cbxMostrarClaveIngresar, 7, 1, 1, 1)
        self.txtCedulaIngresar = QtWidgets.QLineEdit(parent=self.tbIngresar)
        self.txtCedulaIngresar.setMaxLength(10)
        self.txtCedulaIngresar.setObjectName("txtCedulaIngresar")
        self.gridLayout_2.addWidget(self.txtCedulaIngresar, 1, 0, 1, 1)
        self.txtDireccionIngresar = QtWidgets.QLineEdit(parent=self.tbIngresar)
        self.txtDireccionIngresar.setObjectName("txtDireccionIngresar")
        self.gridLayout_2.addWidget(self.txtDireccionIngresar, 5, 0, 1, 1)
        self.lblNombreApellidoIngresar = QtWidgets.QLabel(parent=self.tbIngresar)
        self.lblNombreApellidoIngresar.setObjectName("lblNombreApellidoIngresar")
        self.gridLayout_2.addWidget(self.lblNombreApellidoIngresar, 2, 0, 1, 1)
        self.txtNombreApellidoIngresar = QtWidgets.QLineEdit(parent=self.tbIngresar)
        self.txtNombreApellidoIngresar.setObjectName("txtNombreApellidoIngresar")
        self.gridLayout_2.addWidget(self.txtNombreApellidoIngresar, 3, 0, 1, 1)
        self.lblCedulaIngresar = QtWidgets.QLabel(parent=self.tbIngresar)
        self.lblCedulaIngresar.setObjectName("lblCedulaIngresar")
        self.gridLayout_2.addWidget(self.lblCedulaIngresar, 0, 0, 1, 1)
        self.lblDireccionIngresar = QtWidgets.QLabel(parent=self.tbIngresar)
        self.lblDireccionIngresar.setObjectName("lblDireccionIngresar")
        self.gridLayout_2.addWidget(self.lblDireccionIngresar, 4, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnIngresarEncargado = QtWidgets.QPushButton(parent=self.tbIngresar)
        self.btnIngresarEncargado.setObjectName("btnIngresarEncargado")
        self.horizontalLayout.addWidget(self.btnIngresarEncargado)
        self.btnLimpiarCampos = QtWidgets.QPushButton(parent=self.tbIngresar)
        self.btnLimpiarCampos.setObjectName("btnLimpiarCampos")
        self.horizontalLayout.addWidget(self.btnLimpiarCampos)
        self.gridLayout_2.addLayout(self.horizontalLayout, 9, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 8, 0, 1, 1)
        self.tbEncargado.addTab(self.tbIngresar, "")
        self.tbModificar = QtWidgets.QWidget()
        self.tbModificar.setObjectName("tbModificar")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tbModificar)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lblNombreApellidoModificar = QtWidgets.QLabel(parent=self.tbModificar)
        self.lblNombreApellidoModificar.setObjectName("lblNombreApellidoModificar")
        self.gridLayout_3.addWidget(self.lblNombreApellidoModificar, 2, 0, 1, 1)
        self.lblDireccionModificar = QtWidgets.QLabel(parent=self.tbModificar)
        self.lblDireccionModificar.setObjectName("lblDireccionModificar")
        self.gridLayout_3.addWidget(self.lblDireccionModificar, 4, 0, 1, 1)
        self.txtDireccionModificar = QtWidgets.QLineEdit(parent=self.tbModificar)
        self.txtDireccionModificar.setEnabled(True)
        self.txtDireccionModificar.setObjectName("txtDireccionModificar")
        self.gridLayout_3.addWidget(self.txtDireccionModificar, 5, 0, 1, 1)
        self.txtClaveModificar = QtWidgets.QLineEdit(parent=self.tbModificar)
        self.txtClaveModificar.setEnabled(True)
        self.txtClaveModificar.setObjectName("txtClaveModificar")
        self.gridLayout_3.addWidget(self.txtClaveModificar, 8, 0, 1, 1)
        self.lblClaveModificar = QtWidgets.QLabel(parent=self.tbModificar)
        self.lblClaveModificar.setObjectName("lblClaveModificar")
        self.gridLayout_3.addWidget(self.lblClaveModificar, 6, 0, 1, 1)
        self.lblCedulaModificar = QtWidgets.QLabel(parent=self.tbModificar)
        self.lblCedulaModificar.setObjectName("lblCedulaModificar")
        self.gridLayout_3.addWidget(self.lblCedulaModificar, 0, 0, 1, 1)
        self.txtCedulaModificar = QtWidgets.QLineEdit(parent=self.tbModificar)
        self.txtCedulaModificar.setMaxLength(10)
        self.txtCedulaModificar.setObjectName("txtCedulaModificar")
        self.gridLayout_3.addWidget(self.txtCedulaModificar, 1, 0, 1, 1)
        self.cbxMostrarClaveModificar = QtWidgets.QCheckBox(parent=self.tbModificar)
        self.cbxMostrarClaveModificar.setEnabled(True)
        self.cbxMostrarClaveModificar.setObjectName("cbxMostrarClaveModificar")
        self.gridLayout_3.addWidget(self.cbxMostrarClaveModificar, 8, 1, 1, 1)
        self.txtNombreApellidoModificar = QtWidgets.QLineEdit(parent=self.tbModificar)
        self.txtNombreApellidoModificar.setEnabled(True)
        self.txtNombreApellidoModificar.setObjectName("txtNombreApellidoModificar")
        self.gridLayout_3.addWidget(self.txtNombreApellidoModificar, 3, 0, 1, 1)
        self.btnGuardarCambios = QtWidgets.QPushButton(parent=self.tbModificar)
        self.btnGuardarCambios.setObjectName("btnGuardarCambios")
        self.gridLayout_3.addWidget(self.btnGuardarCambios, 10, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 9, 0, 1, 1)
        self.tbEncargado.addTab(self.tbModificar, "")
        self.tbEliminar = QtWidgets.QWidget()
        self.tbEliminar.setObjectName("tbEliminar")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tbEliminar)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lblDireccionEliminar = QtWidgets.QLabel(parent=self.tbEliminar)
        self.lblDireccionEliminar.setObjectName("lblDireccionEliminar")
        self.gridLayout_4.addWidget(self.lblDireccionEliminar, 4, 0, 1, 1)
        self.txtNombreApellidoEliminar = QtWidgets.QLineEdit(parent=self.tbEliminar)
        self.txtNombreApellidoEliminar.setEnabled(True)
        self.txtNombreApellidoEliminar.setReadOnly(True)
        self.txtNombreApellidoEliminar.setObjectName("txtNombreApellidoEliminar")
        self.gridLayout_4.addWidget(self.txtNombreApellidoEliminar, 3, 0, 1, 1)
        self.txtCedulaEliminar = QtWidgets.QLineEdit(parent=self.tbEliminar)
        self.txtCedulaEliminar.setMaxLength(10)
        self.txtCedulaEliminar.setObjectName("txtCedulaEliminar")
        self.gridLayout_4.addWidget(self.txtCedulaEliminar, 1, 0, 1, 1)
        self.txtDireccionEliminar = QtWidgets.QLineEdit(parent=self.tbEliminar)
        self.txtDireccionEliminar.setEnabled(True)
        self.txtDireccionEliminar.setReadOnly(True)
        self.txtDireccionEliminar.setObjectName("txtDireccionEliminar")
        self.gridLayout_4.addWidget(self.txtDireccionEliminar, 5, 0, 1, 1)
        self.lblNombreApellidoEliminar = QtWidgets.QLabel(parent=self.tbEliminar)
        self.lblNombreApellidoEliminar.setObjectName("lblNombreApellidoEliminar")
        self.gridLayout_4.addWidget(self.lblNombreApellidoEliminar, 2, 0, 1, 1)
        self.lblCedulaEliminar = QtWidgets.QLabel(parent=self.tbEliminar)
        self.lblCedulaEliminar.setObjectName("lblCedulaEliminar")
        self.gridLayout_4.addWidget(self.lblCedulaEliminar, 0, 0, 1, 1)
        self.btnEliminar = QtWidgets.QPushButton(parent=self.tbEliminar)
        self.btnEliminar.setObjectName("btnEliminar")
        self.gridLayout_4.addWidget(self.btnEliminar, 7, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 6, 0, 1, 1)
        self.tbEncargado.addTab(self.tbEliminar, "")
        self.tbListar = QtWidgets.QWidget()
        self.tbListar.setObjectName("tbListar")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tbListar)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.jgdListaEncargados = QtWidgets.QTableWidget(parent=self.tbListar)
        self.jgdListaEncargados.setObjectName("jgdListaEncargados")
        self.jgdListaEncargados.setColumnCount(0)
        self.jgdListaEncargados.setRowCount(0)
        self.jgdListaEncargados.horizontalHeader().setCascadingSectionResizes(True)
        self.jgdListaEncargados.horizontalHeader().setDefaultSectionSize(420)
        self.jgdListaEncargados.horizontalHeader().setMinimumSectionSize(100)
        self.jgdListaEncargados.verticalHeader().setCascadingSectionResizes(True)
        self.gridLayout_5.addWidget(self.jgdListaEncargados, 0, 0, 1, 1)
        self.tbEncargado.addTab(self.tbListar, "")
        self.gridLayout.addWidget(self.tbEncargado, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=Ui_GestionEncargado)
        self.label.setMinimumSize(QtCore.QSize(500, 700))
        self.label.setMaximumSize(QtCore.QSize(500, 700))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("./Vistas/logoRestaurante.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)

        self.retranslateUi(Ui_GestionEncargado)
        self.tbEncargado.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Ui_GestionEncargado)
        Ui_GestionEncargado.setTabOrder(self.tbEncargado, self.txtCedulaIngresar)
        Ui_GestionEncargado.setTabOrder(self.txtCedulaIngresar, self.txtNombreApellidoIngresar)
        Ui_GestionEncargado.setTabOrder(self.txtNombreApellidoIngresar, self.txtDireccionIngresar)
        Ui_GestionEncargado.setTabOrder(self.txtDireccionIngresar, self.txtClaveIngresar)
        Ui_GestionEncargado.setTabOrder(self.txtClaveIngresar, self.cbxMostrarClaveIngresar)
        Ui_GestionEncargado.setTabOrder(self.cbxMostrarClaveIngresar, self.btnIngresarEncargado)
        Ui_GestionEncargado.setTabOrder(self.btnIngresarEncargado, self.btnLimpiarCampos)
        Ui_GestionEncargado.setTabOrder(self.btnLimpiarCampos, self.txtCedulaModificar)
        Ui_GestionEncargado.setTabOrder(self.txtCedulaModificar, self.txtNombreApellidoModificar)
        Ui_GestionEncargado.setTabOrder(self.txtNombreApellidoModificar, self.txtDireccionModificar)
        Ui_GestionEncargado.setTabOrder(self.txtDireccionModificar, self.txtClaveModificar)
        Ui_GestionEncargado.setTabOrder(self.txtClaveModificar, self.cbxMostrarClaveModificar)
        Ui_GestionEncargado.setTabOrder(self.cbxMostrarClaveModificar, self.btnGuardarCambios)
        Ui_GestionEncargado.setTabOrder(self.btnGuardarCambios, self.txtCedulaEliminar)
        Ui_GestionEncargado.setTabOrder(self.txtCedulaEliminar, self.txtNombreApellidoEliminar)
        Ui_GestionEncargado.setTabOrder(self.txtNombreApellidoEliminar, self.txtDireccionEliminar)
        Ui_GestionEncargado.setTabOrder(self.txtDireccionEliminar, self.btnEliminar)
        Ui_GestionEncargado.setTabOrder(self.btnEliminar, self.jgdListaEncargados)

    def retranslateUi(self, Ui_GestionEncargado):
        _translate = QtCore.QCoreApplication.translate
        Ui_GestionEncargado.setWindowTitle(_translate("Ui_GestionEncargado", "Encargado"))
        self.lblClaveIngresar.setText(_translate("Ui_GestionEncargado", "Contraseña"))
        self.txtClaveIngresar.setPlaceholderText(_translate("Ui_GestionEncargado", "Ingrese constraseña"))
        self.cbxMostrarClaveIngresar.setText(_translate("Ui_GestionEncargado", "Mostrar contraseña"))
        self.txtCedulaIngresar.setPlaceholderText(_translate("Ui_GestionEncargado", "Ingrese cédula"))
        self.txtDireccionIngresar.setPlaceholderText(_translate("Ui_GestionEncargado", "Ingrese dirección"))
        self.lblNombreApellidoIngresar.setText(_translate("Ui_GestionEncargado", "Nombre y Apellido"))
        self.txtNombreApellidoIngresar.setPlaceholderText(_translate("Ui_GestionEncargado", "Ingrese nombre y apellido"))
        self.lblCedulaIngresar.setText(_translate("Ui_GestionEncargado", "Cédula"))
        self.lblDireccionIngresar.setText(_translate("Ui_GestionEncargado", "Dirección"))
        self.btnIngresarEncargado.setText(_translate("Ui_GestionEncargado", "Ingresar encargado"))
        self.btnLimpiarCampos.setText(_translate("Ui_GestionEncargado", "Limpiar campos"))
        self.tbEncargado.setTabText(self.tbEncargado.indexOf(self.tbIngresar), _translate("Ui_GestionEncargado", "Ingresar"))
        self.lblNombreApellidoModificar.setText(_translate("Ui_GestionEncargado", "Nombre y Apellido"))
        self.lblDireccionModificar.setText(_translate("Ui_GestionEncargado", "Dirección"))
        self.lblClaveModificar.setText(_translate("Ui_GestionEncargado", "Contraseña"))
        self.lblCedulaModificar.setText(_translate("Ui_GestionEncargado", "Cédula"))
        self.txtCedulaModificar.setPlaceholderText(_translate("Ui_GestionEncargado", "Ingrese cédula"))
        self.cbxMostrarClaveModificar.setText(_translate("Ui_GestionEncargado", "Mostrar contraseña"))
        self.btnGuardarCambios.setText(_translate("Ui_GestionEncargado", "Guardar cambios"))
        self.tbEncargado.setTabText(self.tbEncargado.indexOf(self.tbModificar), _translate("Ui_GestionEncargado", "Modificar"))
        self.lblDireccionEliminar.setText(_translate("Ui_GestionEncargado", "Dirección"))
        self.txtCedulaEliminar.setPlaceholderText(_translate("Ui_GestionEncargado", "Ingrese cédula"))
        self.lblNombreApellidoEliminar.setText(_translate("Ui_GestionEncargado", "Nombre y Apellido"))
        self.lblCedulaEliminar.setText(_translate("Ui_GestionEncargado", "Cédula"))
        self.btnEliminar.setText(_translate("Ui_GestionEncargado", "Eliminar encargado"))
        self.tbEncargado.setTabText(self.tbEncargado.indexOf(self.tbEliminar), _translate("Ui_GestionEncargado", "Eliminar"))
        self.tbEncargado.setTabText(self.tbEncargado.indexOf(self.tbListar), _translate("Ui_GestionEncargado", "Listar"))
