# Form implementation generated from reading ui file 'Ui_InicioSesion.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_InicioSesion(object):
    def setupUi(self, Ui_InicioSesion):
        Ui_InicioSesion.setObjectName("Ui_InicioSesion")
        Ui_InicioSesion.resize(1280, 600)
        Ui_InicioSesion.setStyleSheet("QWidget{\n"
"background-color:white;\n"
"}\n"
"\n"
"QLabel{\n"
"font-family:\"Sans-serif\";\n"
"font-size:14px;\n"
"padding:5px;\n"
"\n"
"}\n"
"\n"
"QLineEdit{\n"
"font-family:\"Sans-serif\";\n"
"font-size:14px;\n"
"padding:10px 10px;\n"
"border-radius:10px;\n"
"margin-left:10px;\n"
"margin-right: 10px;\n"
"border:2px solid rgb(228, 232, 235);\n"
"}\n"
"\n"
"QPushButton{\n"
"font-family:\"Sans-serif\";\n"
"background-color: #E4E8EB;\n"
"padding: 10px 10px;\n"
"border-radius: 10px;\n"
"margin-left:10px;\n"
"margin-right:10px;\n"
"}\n"
"\n"
"\n"
"QLineEdit:hover{\n"
"border:2px solid black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:2px solid black;\n"
"}\n"
"\n"
"#lblInicioSesion{\n"
"font-size:20px;\n"
"}\n"
"\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(Ui_InicioSesion)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.txtClave = QtWidgets.QLineEdit(parent=Ui_InicioSesion)
        self.txtClave.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.txtClave.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtClave.setObjectName("txtClave")
        self.gridLayout_2.addWidget(self.txtClave, 7, 0, 1, 1)
        self.txtUsuario = QtWidgets.QLineEdit(parent=Ui_InicioSesion)
        self.txtUsuario.setMaxLength(10)
        self.txtUsuario.setObjectName("txtUsuario")
        self.gridLayout_2.addWidget(self.txtUsuario, 4, 0, 1, 1)
        self.btnEntrar = QtWidgets.QPushButton(parent=Ui_InicioSesion)
        self.btnEntrar.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.btnEntrar.setObjectName("btnEntrar")
        self.gridLayout_2.addWidget(self.btnEntrar, 10, 0, 1, 2)
        self.lblClave = QtWidgets.QLabel(parent=Ui_InicioSesion)
        self.lblClave.setObjectName("lblClave")
        self.gridLayout_2.addWidget(self.lblClave, 6, 0, 1, 2)
        self.lblInicioSesion = QtWidgets.QLabel(parent=Ui_InicioSesion)
        font = QtGui.QFont()
        font.setFamily("Sans-serif")
        font.setPointSize(-1)
        self.lblInicioSesion.setFont(font)
        self.lblInicioSesion.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblInicioSesion.setObjectName("lblInicioSesion")
        self.gridLayout_2.addWidget(self.lblInicioSesion, 2, 0, 1, 2)
        self.lblUsuario = QtWidgets.QLabel(parent=Ui_InicioSesion)
        self.lblUsuario.setObjectName("lblUsuario")
        self.gridLayout_2.addWidget(self.lblUsuario, 3, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 9, 0, 1, 1)
        self.cbxMostrarClave = QtWidgets.QCheckBox(parent=Ui_InicioSesion)
        self.cbxMostrarClave.setObjectName("cbxMostrarClave")
        self.gridLayout_2.addWidget(self.cbxMostrarClave, 7, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(Ui_InicioSesion)
        QtCore.QMetaObject.connectSlotsByName(Ui_InicioSesion)
        Ui_InicioSesion.setTabOrder(self.txtUsuario, self.txtClave)
        Ui_InicioSesion.setTabOrder(self.txtClave, self.cbxMostrarClave)
        Ui_InicioSesion.setTabOrder(self.cbxMostrarClave, self.btnEntrar)

    def retranslateUi(self, Ui_InicioSesion):
        _translate = QtCore.QCoreApplication.translate
        Ui_InicioSesion.setWindowTitle(_translate("Ui_InicioSesion", "Inicio sesion"))
        self.txtClave.setPlaceholderText(_translate("Ui_InicioSesion", "Ingrese contraseña"))
        self.txtUsuario.setPlaceholderText(_translate("Ui_InicioSesion", "Ingrese cédula"))
        self.btnEntrar.setText(_translate("Ui_InicioSesion", "Entrar"))
        self.lblClave.setText(_translate("Ui_InicioSesion", "Contraseña"))
        self.lblInicioSesion.setText(_translate("Ui_InicioSesion", "Inicio Sesión"))
        self.lblUsuario.setText(_translate("Ui_InicioSesion", "Usuario"))
        self.cbxMostrarClave.setText(_translate("Ui_InicioSesion", "Mostrar contraseña"))
