# Form implementation generated from reading ui file 'Ui_Main.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Ui_Main):
        Ui_Main.setObjectName("Ui_Main")
        Ui_Main.resize(1366, 768)
        Ui_Main.setMinimumSize(QtCore.QSize(800, 600))
        Ui_Main.setMaximumSize(QtCore.QSize(1366, 768))
        Ui_Main.setStyleSheet("QMainWindow{\n"
"    background-color: white;\n"
"}\n"
"\n"
"/* QToolBar */\n"
"QToolBar{\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QToolButton{\n"
"    font-family: \"Sans-serif\";\n"
"    font-size: 14px;\n"
"    padding: 10px;\n"
"    margin: 5px;\n"
"    border-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QToolButton:hover{\n"
"    background-color:#E4E8EB;\n"
"}\n"
"\n"
"/* QMenuBar */\n"
"QMenuBar{\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QMenuBar::item{\n"
"    font-family: \"Sans-serif\";\n"
"    font-size: 14px;\n"
"    padding: 5px 10px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QMenuBar::item:selected{\n"
"    background: #E4E8EB;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"/* QMenu */\n"
"QMenu{\n"
"    background-color: white;\n"
"    border: 2px solid rgb(228, 232, 235);\n"
"}\n"
"\n"
"QMenu::item{\n"
"    font-family: \"Sans-serif\";\n"
"    font-size: 14px;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QMenu::item:selected{\n"
"    background-color: #E4E8EB;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QLabel{\n"
"font-family:\"Sans-serif\";\n"
"font-size:25px;\n"
"padding:5px;\n"
"\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=Ui_Main)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("./Vistas/logoRestaurante.jpg"))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        Ui_Main.setCentralWidget(self.centralwidget)
        self.jmbMenu = QtWidgets.QMenuBar(parent=Ui_Main)
        self.jmbMenu.setGeometry(QtCore.QRect(0, 0, 1407, 41))
        self.jmbMenu.setObjectName("jmbMenu")
        self.jmbMenuPrincipal = QtWidgets.QMenu(parent=self.jmbMenu)
        self.jmbMenuPrincipal.setObjectName("jmbMenuPrincipal")
        self.jmbReserva = QtWidgets.QMenu(parent=self.jmbMenu)
        self.jmbReserva.setObjectName("jmbReserva")
        self.jmbDisponibilidad = QtWidgets.QMenu(parent=self.jmbMenu)
        self.jmbDisponibilidad.setObjectName("jmbDisponibilidad")
        self.jmbCarta = QtWidgets.QMenu(parent=self.jmbMenu)
        self.jmbCarta.setObjectName("jmbCarta")
        self.jmbProducto = QtWidgets.QMenu(parent=self.jmbMenu)
        self.jmbProducto.setObjectName("jmbProducto")
        self.jmbIngrediente = QtWidgets.QMenu(parent=self.jmbMenu)
        self.jmbIngrediente.setObjectName("jmbIngrediente")
        self.jmbPersonal = QtWidgets.QMenu(parent=self.jmbMenu)
        self.jmbPersonal.setObjectName("jmbPersonal")
        self.jmbReportes = QtWidgets.QMenu(parent=self.jmbMenu)
        self.jmbReportes.setObjectName("jmbReportes")
        Ui_Main.setMenuBar(self.jmbMenu)
        self.statusbar = QtWidgets.QStatusBar(parent=Ui_Main)
        self.statusbar.setObjectName("statusbar")
        Ui_Main.setStatusBar(self.statusbar)
        self.jtbAccesosRapidos = QtWidgets.QToolBar(parent=Ui_Main)
        self.jtbAccesosRapidos.setObjectName("jtbAccesosRapidos")
        Ui_Main.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.jtbAccesosRapidos)
        self.jmbConfiguracion = QtGui.QAction(parent=Ui_Main)
        self.jmbConfiguracion.setObjectName("jmbConfiguracion")
        self.jmbSalir = QtGui.QAction(parent=Ui_Main)
        self.jmbSalir.setObjectName("jmbSalir")
        self.jtbReservaIngresar = QtGui.QAction(parent=Ui_Main)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./Vistas/reserva.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.jtbReservaIngresar.setIcon(icon)
        self.jtbReservaIngresar.setObjectName("jtbReservaIngresar")
        self.jtbDisponibilidadIngresar = QtGui.QAction(parent=Ui_Main)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./Vistas/disponibilidad.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.jtbDisponibilidadIngresar.setIcon(icon1)
        self.jtbDisponibilidadIngresar.setObjectName("jtbDisponibilidadIngresar")
        self.jmbReservaIngresar = QtGui.QAction(parent=Ui_Main)
        self.jmbReservaIngresar.setObjectName("jmbReservaIngresar")
        self.jmbReservaModificar = QtGui.QAction(parent=Ui_Main)
        self.jmbReservaModificar.setObjectName("jmbReservaModificar")
        self.jmbReservaEliminar = QtGui.QAction(parent=Ui_Main)
        self.jmbReservaEliminar.setObjectName("jmbReservaEliminar")
        self.jmbReservaListar = QtGui.QAction(parent=Ui_Main)
        self.jmbReservaListar.setObjectName("jmbReservaListar")
        self.jmbDisponibilidadIngresar = QtGui.QAction(parent=Ui_Main)
        self.jmbDisponibilidadIngresar.setObjectName("jmbDisponibilidadIngresar")
        self.jmbDisponibilidadModificar = QtGui.QAction(parent=Ui_Main)
        self.jmbDisponibilidadModificar.setObjectName("jmbDisponibilidadModificar")
        self.jmbDisponibilidadEliminar = QtGui.QAction(parent=Ui_Main)
        self.jmbDisponibilidadEliminar.setObjectName("jmbDisponibilidadEliminar")
        self.jmbDisponibilidadListar = QtGui.QAction(parent=Ui_Main)
        self.jmbDisponibilidadListar.setObjectName("jmbDisponibilidadListar")
        self.jmbCartaIngresar = QtGui.QAction(parent=Ui_Main)
        self.jmbCartaIngresar.setObjectName("jmbCartaIngresar")
        self.jmbCartaModificar = QtGui.QAction(parent=Ui_Main)
        self.jmbCartaModificar.setObjectName("jmbCartaModificar")
        self.jmbCartaEliminar = QtGui.QAction(parent=Ui_Main)
        self.jmbCartaEliminar.setObjectName("jmbCartaEliminar")
        self.jmbCartaListar = QtGui.QAction(parent=Ui_Main)
        self.jmbCartaListar.setObjectName("jmbCartaListar")
        self.jmbProductoIngresar = QtGui.QAction(parent=Ui_Main)
        self.jmbProductoIngresar.setObjectName("jmbProductoIngresar")
        self.jmbProductoModificar = QtGui.QAction(parent=Ui_Main)
        self.jmbProductoModificar.setObjectName("jmbProductoModificar")
        self.jmbProductoEliminar = QtGui.QAction(parent=Ui_Main)
        self.jmbProductoEliminar.setObjectName("jmbProductoEliminar")
        self.jmbProductoListar = QtGui.QAction(parent=Ui_Main)
        self.jmbProductoListar.setObjectName("jmbProductoListar")
        self.jmbIngredienteIngresar = QtGui.QAction(parent=Ui_Main)
        self.jmbIngredienteIngresar.setObjectName("jmbIngredienteIngresar")
        self.jmbIngredienteModificar = QtGui.QAction(parent=Ui_Main)
        self.jmbIngredienteModificar.setObjectName("jmbIngredienteModificar")
        self.jmbIngredienteEliminar = QtGui.QAction(parent=Ui_Main)
        self.jmbIngredienteEliminar.setObjectName("jmbIngredienteEliminar")
        self.jmbIngredienteListar = QtGui.QAction(parent=Ui_Main)
        self.jmbIngredienteListar.setObjectName("jmbIngredienteListar")
        self.jmbPersonalIngresar = QtGui.QAction(parent=Ui_Main)
        self.jmbPersonalIngresar.setObjectName("jmbPersonalIngresar")
        self.jmbPersonalModificar = QtGui.QAction(parent=Ui_Main)
        self.jmbPersonalModificar.setObjectName("jmbPersonalModificar")
        self.jmbPersonalEliminar = QtGui.QAction(parent=Ui_Main)
        self.jmbPersonalEliminar.setObjectName("jmbPersonalEliminar")
        self.jmbPersonalListar = QtGui.QAction(parent=Ui_Main)
        self.jmbPersonalListar.setObjectName("jmbPersonalListar")
        self.jmbAcercaDe = QtGui.QAction(parent=Ui_Main)
        self.jmbAcercaDe.setObjectName("jmbAcercaDe")
        self.jmbReporteDinero = QtGui.QAction(parent=Ui_Main)
        self.jmbReporteDinero.setObjectName("jmbReporteDinero")
        self.jmbReporteProducto = QtGui.QAction(parent=Ui_Main)
        self.jmbReporteProducto.setObjectName("jmbReporteProducto")
        self.jmbReporteConcurrencia = QtGui.QAction(parent=Ui_Main)
        self.jmbReporteConcurrencia.setObjectName("jmbReporteConcurrencia")
        self.jmbMenuPrincipal.addAction(self.jmbConfiguracion)
        self.jmbMenuPrincipal.addAction(self.jmbAcercaDe)
        self.jmbMenuPrincipal.addSeparator()
        self.jmbMenuPrincipal.addAction(self.jmbSalir)
        self.jmbReserva.addAction(self.jmbReservaIngresar)
        self.jmbReserva.addAction(self.jmbReservaModificar)
        self.jmbReserva.addAction(self.jmbReservaEliminar)
        self.jmbReserva.addAction(self.jmbReservaListar)
        self.jmbDisponibilidad.addAction(self.jmbDisponibilidadIngresar)
        self.jmbDisponibilidad.addAction(self.jmbDisponibilidadModificar)
        self.jmbDisponibilidad.addAction(self.jmbDisponibilidadEliminar)
        self.jmbDisponibilidad.addAction(self.jmbDisponibilidadListar)
        self.jmbCarta.addAction(self.jmbCartaIngresar)
        self.jmbCarta.addAction(self.jmbCartaModificar)
        self.jmbCarta.addAction(self.jmbCartaEliminar)
        self.jmbCarta.addAction(self.jmbCartaListar)
        self.jmbProducto.addAction(self.jmbProductoIngresar)
        self.jmbProducto.addAction(self.jmbProductoModificar)
        self.jmbProducto.addAction(self.jmbProductoEliminar)
        self.jmbProducto.addAction(self.jmbProductoListar)
        self.jmbIngrediente.addAction(self.jmbIngredienteIngresar)
        self.jmbIngrediente.addAction(self.jmbIngredienteModificar)
        self.jmbIngrediente.addAction(self.jmbIngredienteEliminar)
        self.jmbIngrediente.addAction(self.jmbIngredienteListar)
        self.jmbPersonal.addAction(self.jmbPersonalIngresar)
        self.jmbPersonal.addAction(self.jmbPersonalModificar)
        self.jmbPersonal.addAction(self.jmbPersonalEliminar)
        self.jmbPersonal.addAction(self.jmbPersonalListar)
        self.jmbReportes.addAction(self.jmbReporteDinero)
        self.jmbReportes.addAction(self.jmbReporteProducto)
        self.jmbReportes.addAction(self.jmbReporteConcurrencia)
        self.jmbMenu.addAction(self.jmbMenuPrincipal.menuAction())
        self.jmbMenu.addAction(self.jmbReserva.menuAction())
        self.jmbMenu.addAction(self.jmbDisponibilidad.menuAction())
        self.jmbMenu.addAction(self.jmbCarta.menuAction())
        self.jmbMenu.addAction(self.jmbProducto.menuAction())
        self.jmbMenu.addAction(self.jmbIngrediente.menuAction())
        self.jmbMenu.addAction(self.jmbPersonal.menuAction())
        self.jmbMenu.addAction(self.jmbReportes.menuAction())
        self.jtbAccesosRapidos.addAction(self.jtbReservaIngresar)
        self.jtbAccesosRapidos.addAction(self.jtbDisponibilidadIngresar)

        self.retranslateUi(Ui_Main)
        QtCore.QMetaObject.connectSlotsByName(Ui_Main)

    def retranslateUi(self, Ui_Main):
        _translate = QtCore.QCoreApplication.translate
        Ui_Main.setWindowTitle(_translate("Ui_Main", "Restaurante"))
        self.jmbMenuPrincipal.setTitle(_translate("Ui_Main", "Menu"))
        self.jmbReserva.setTitle(_translate("Ui_Main", "Reserva"))
        self.jmbDisponibilidad.setTitle(_translate("Ui_Main", "Disponibilidad"))
        self.jmbCarta.setTitle(_translate("Ui_Main", "Carta"))
        self.jmbProducto.setTitle(_translate("Ui_Main", "Producto"))
        self.jmbIngrediente.setTitle(_translate("Ui_Main", "Ingrediente"))
        self.jmbPersonal.setTitle(_translate("Ui_Main", "Personal"))
        self.jmbReportes.setTitle(_translate("Ui_Main", "Reportes"))
        self.jtbAccesosRapidos.setWindowTitle(_translate("Ui_Main", "toolBar"))
        self.jmbConfiguracion.setText(_translate("Ui_Main", "Configuración"))
        self.jmbSalir.setText(_translate("Ui_Main", "Salir"))
        self.jtbReservaIngresar.setText(_translate("Ui_Main", "Ingresar reserva"))
        self.jtbDisponibilidadIngresar.setText(_translate("Ui_Main", "Ingresar disponibilidad"))
        self.jmbReservaIngresar.setText(_translate("Ui_Main", "Ingresar"))
        self.jmbReservaModificar.setText(_translate("Ui_Main", "Modificar"))
        self.jmbReservaEliminar.setText(_translate("Ui_Main", "Eliminar"))
        self.jmbReservaListar.setText(_translate("Ui_Main", "Listar"))
        self.jmbDisponibilidadIngresar.setText(_translate("Ui_Main", "Ingresar"))
        self.jmbDisponibilidadModificar.setText(_translate("Ui_Main", "Modificar"))
        self.jmbDisponibilidadEliminar.setText(_translate("Ui_Main", "Eliminar"))
        self.jmbDisponibilidadListar.setText(_translate("Ui_Main", "Listar"))
        self.jmbCartaIngresar.setText(_translate("Ui_Main", "Ingresar"))
        self.jmbCartaModificar.setText(_translate("Ui_Main", "Modificar"))
        self.jmbCartaEliminar.setText(_translate("Ui_Main", "Eliminar"))
        self.jmbCartaListar.setText(_translate("Ui_Main", "Listar"))
        self.jmbProductoIngresar.setText(_translate("Ui_Main", "Ingresar"))
        self.jmbProductoModificar.setText(_translate("Ui_Main", "Modificar"))
        self.jmbProductoEliminar.setText(_translate("Ui_Main", "Eliminar"))
        self.jmbProductoListar.setText(_translate("Ui_Main", "Listar"))
        self.jmbIngredienteIngresar.setText(_translate("Ui_Main", "Ingresar"))
        self.jmbIngredienteModificar.setText(_translate("Ui_Main", "Modificar"))
        self.jmbIngredienteEliminar.setText(_translate("Ui_Main", "Eliminar"))
        self.jmbIngredienteListar.setText(_translate("Ui_Main", "Listar"))
        self.jmbPersonalIngresar.setText(_translate("Ui_Main", "Ingresar"))
        self.jmbPersonalModificar.setText(_translate("Ui_Main", "Modificar"))
        self.jmbPersonalEliminar.setText(_translate("Ui_Main", "Eliminar"))
        self.jmbPersonalListar.setText(_translate("Ui_Main", "Listar"))
        self.jmbAcercaDe.setText(_translate("Ui_Main", "Acerca de"))
        self.jmbReporteDinero.setText(_translate("Ui_Main", "Dinero generado por meses"))
        self.jmbReporteProducto.setText(_translate("Ui_Main", "Producto más demandado por meses"))
        self.jmbReporteConcurrencia.setText(_translate("Ui_Main", "Días más concurrido por meses"))
