# Form implementation generated from reading ui file 'Ui_Reserva.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Reserva(object):
    def setupUi(self, Ui_Reserva):
        Ui_Reserva.setObjectName("Ui_Reserva")
        Ui_Reserva.resize(1280, 800)
        Ui_Reserva.setMinimumSize(QtCore.QSize(800, 600))
        Ui_Reserva.setMaximumSize(QtCore.QSize(1366, 768))
        Ui_Reserva.setStyleSheet("QWidget{\n"
"background-color:white;\n"
"}\n"
"\n"
"QLabel{\n"
"font-family:\"Sans-serif\";\n"
"font-size:14px;\n"
"padding:5px;\n"
"\n"
"}\n"
"\n"
"QDoubleSpinBox{\n"
"font-family:\"Sans-serif\";\n"
"font-size:14px;\n"
"padding:10px 10px;\n"
"border-radius:10px;\n"
"border:2px solid rgb(228, 232, 235);\n"
"}\n"
"\n"
"QSpinBox{\n"
"font-family:\"Sans-serif\";\n"
"font-size:14px;\n"
"padding:10px 10px;\n"
"border-radius:10px;\n"
"border:2px solid rgb(228, 232, 235);\n"
"}\n"
"\n"
"\n"
"QComboBox{\n"
"font-family:\"Sans-serif\";\n"
"font-size:14px;\n"
"padding:10px 10px;\n"
"border-radius:10px;\n"
"border:2px solid rgb(228, 232, 235);\n"
"}\n"
"\n"
"QLineEdit{\n"
"font-family:\"Sans-serif\";\n"
"font-size:14px;\n"
"padding:10px 10px;\n"
"border-radius:10px;\n"
"border:2px solid rgb(228, 232, 235);\n"
"}\n"
"\n"
"QPushButton{\n"
"font-family:\"Sans-serif\";\n"
"background-color: #E4E8EB;\n"
"padding: 10px 10px;\n"
"border-radius: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit:hover{\n"
"border:2px solid black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:2px solid black;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Ui_Reserva)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=Ui_Reserva)
        self.label.setMinimumSize(QtCore.QSize(500, 700))
        self.label.setMaximumSize(QtCore.QSize(500, 700))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("./Vistas/logoRestaurante.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.tbReserva = QtWidgets.QTabWidget(parent=Ui_Reserva)
        self.tbReserva.setObjectName("tbReserva")
        self.tbIngresar = QtWidgets.QWidget()
        self.tbIngresar.setObjectName("tbIngresar")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tbIngresar)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cmbAgregarProductosIngresar = QtWidgets.QComboBox(parent=self.tbIngresar)
        self.cmbAgregarProductosIngresar.setObjectName("cmbAgregarProductosIngresar")
        self.horizontalLayout.addWidget(self.cmbAgregarProductosIngresar)
        self.sbCantidadProductoIngresar = QtWidgets.QSpinBox(parent=self.tbIngresar)
        self.sbCantidadProductoIngresar.setObjectName("sbCantidadProductoIngresar")
        self.horizontalLayout.addWidget(self.sbCantidadProductoIngresar)
        self.gridLayout_2.addLayout(self.horizontalLayout, 15, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnGuardarCambiosPedidoIngresar = QtWidgets.QPushButton(parent=self.tbIngresar)
        self.btnGuardarCambiosPedidoIngresar.setObjectName("btnGuardarCambiosPedidoIngresar")
        self.horizontalLayout_5.addWidget(self.btnGuardarCambiosPedidoIngresar)
        self.btnEliminarPedidoIngresar = QtWidgets.QPushButton(parent=self.tbIngresar)
        self.btnEliminarPedidoIngresar.setObjectName("btnEliminarPedidoIngresar")
        self.horizontalLayout_5.addWidget(self.btnEliminarPedidoIngresar)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 21, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cmbTurnoIngresar = QtWidgets.QComboBox(parent=self.tbIngresar)
        self.cmbTurnoIngresar.setObjectName("cmbTurnoIngresar")
        self.gridLayout_3.addWidget(self.cmbTurnoIngresar, 1, 1, 1, 1)
        self.lblTurnoIngresar = QtWidgets.QLabel(parent=self.tbIngresar)
        self.lblTurnoIngresar.setObjectName("lblTurnoIngresar")
        self.gridLayout_3.addWidget(self.lblTurnoIngresar, 0, 1, 1, 1)
        self.lblNumeroReservaIngresar = QtWidgets.QLabel(parent=self.tbIngresar)
        self.lblNumeroReservaIngresar.setObjectName("lblNumeroReservaIngresar")
        self.gridLayout_3.addWidget(self.lblNumeroReservaIngresar, 0, 0, 1, 1)
        self.txtNumeroReservaIngresar = QtWidgets.QLineEdit(parent=self.tbIngresar)
        self.txtNumeroReservaIngresar.setEnabled(False)
        self.txtNumeroReservaIngresar.setObjectName("txtNumeroReservaIngresar")
        self.gridLayout_3.addWidget(self.txtNumeroReservaIngresar, 1, 0, 1, 1)
        self.lblNumeroComensalesIngresar = QtWidgets.QLabel(parent=self.tbIngresar)
        self.lblNumeroComensalesIngresar.setObjectName("lblNumeroComensalesIngresar")
        self.gridLayout_3.addWidget(self.lblNumeroComensalesIngresar, 0, 2, 1, 1)
        self.sbNumeroComensalesIngresar = QtWidgets.QSpinBox(parent=self.tbIngresar)
        self.sbNumeroComensalesIngresar.setObjectName("sbNumeroComensalesIngresar")
        self.gridLayout_3.addWidget(self.sbNumeroComensalesIngresar, 1, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 6, 0, 1, 1)
        self.dtpFechaIngresar = QtWidgets.QCalendarWidget(parent=self.tbIngresar)
        self.dtpFechaIngresar.setStyleSheet("QCalendarWidget QToolButton {\n"
"    color: black;\n"
"    background-color: #e6e6e6;\n"
"    border: none;\n"
"    margin: 5px;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QCalendarWidget QWidget#qt_calendar_navigationbar {\n"
"    background-color: #e6e6e6;\n"
"}\n"
"\n"
"QCalendarWidget QTableView {\n"
"    selection-background-color: #e6e6e6;\n"
"}\n"
"\n"
"\n"
"QCalendarWidget QMenu::item:selected {\n"
"    background-color: #e6e6e6; /* Color de fondo de la selección */\n"
"}")
        self.dtpFechaIngresar.setObjectName("dtpFechaIngresar")
        self.gridLayout_2.addWidget(self.dtpFechaIngresar, 1, 0, 2, 1)
        self.btnAgregarProductoIngresar = QtWidgets.QPushButton(parent=self.tbIngresar)
        self.btnAgregarProductoIngresar.setObjectName("btnAgregarProductoIngresar")
        self.gridLayout_2.addWidget(self.btnAgregarProductoIngresar, 16, 0, 1, 1)
        self.btnReservar = QtWidgets.QPushButton(parent=self.tbIngresar)
        self.btnReservar.setObjectName("btnReservar")
        self.gridLayout_2.addWidget(self.btnReservar, 23, 0, 1, 1)
        self.lblEliminarPedidoIngresar = QtWidgets.QLabel(parent=self.tbIngresar)
        self.lblEliminarPedidoIngresar.setObjectName("lblEliminarPedidoIngresar")
        self.gridLayout_2.addWidget(self.lblEliminarPedidoIngresar, 17, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cmbPedidoIngresar = QtWidgets.QComboBox(parent=self.tbIngresar)
        self.cmbPedidoIngresar.setObjectName("cmbPedidoIngresar")
        self.horizontalLayout_2.addWidget(self.cmbPedidoIngresar)
        self.sbCantidadPedidoIngresar = QtWidgets.QSpinBox(parent=self.tbIngresar)
        self.sbCantidadPedidoIngresar.setObjectName("sbCantidadPedidoIngresar")
        self.horizontalLayout_2.addWidget(self.sbCantidadPedidoIngresar)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 20, 0, 1, 1)
        self.lblFechaIngresar = QtWidgets.QLabel(parent=self.tbIngresar)
        self.lblFechaIngresar.setObjectName("lblFechaIngresar")
        self.gridLayout_2.addWidget(self.lblFechaIngresar, 0, 0, 1, 1)
        self.lblAgregarProductoIngresar = QtWidgets.QLabel(parent=self.tbIngresar)
        self.lblAgregarProductoIngresar.setObjectName("lblAgregarProductoIngresar")
        self.gridLayout_2.addWidget(self.lblAgregarProductoIngresar, 14, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 22, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 3, 0, 1, 1)
        self.tbReserva.addTab(self.tbIngresar, "")
        self.tbModificar = QtWidgets.QWidget()
        self.tbModificar.setObjectName("tbModificar")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tbModificar)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btnAgregarProductoModificar = QtWidgets.QPushButton(parent=self.tbModificar)
        self.btnAgregarProductoModificar.setObjectName("btnAgregarProductoModificar")
        self.gridLayout_4.addWidget(self.btnAgregarProductoModificar, 15, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btnGuardarCambiosPedidoModificar = QtWidgets.QPushButton(parent=self.tbModificar)
        self.btnGuardarCambiosPedidoModificar.setObjectName("btnGuardarCambiosPedidoModificar")
        self.horizontalLayout_6.addWidget(self.btnGuardarCambiosPedidoModificar)
        self.btnEliminarPedidoModificar = QtWidgets.QPushButton(parent=self.tbModificar)
        self.btnEliminarPedidoModificar.setObjectName("btnEliminarPedidoModificar")
        self.horizontalLayout_6.addWidget(self.btnEliminarPedidoModificar)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 18, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cmbPedidoModificar = QtWidgets.QComboBox(parent=self.tbModificar)
        self.cmbPedidoModificar.setObjectName("cmbPedidoModificar")
        self.horizontalLayout_4.addWidget(self.cmbPedidoModificar)
        self.sbCantidadPedidoModificar = QtWidgets.QSpinBox(parent=self.tbModificar)
        self.sbCantidadPedidoModificar.setObjectName("sbCantidadPedidoModificar")
        self.horizontalLayout_4.addWidget(self.sbCantidadPedidoModificar)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 17, 0, 1, 1)
        self.lblAgregarProductoModificar = QtWidgets.QLabel(parent=self.tbModificar)
        self.lblAgregarProductoModificar.setObjectName("lblAgregarProductoModificar")
        self.gridLayout_4.addWidget(self.lblAgregarProductoModificar, 13, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cmbAgregarProductoModificar = QtWidgets.QComboBox(parent=self.tbModificar)
        self.cmbAgregarProductoModificar.setObjectName("cmbAgregarProductoModificar")
        self.horizontalLayout_3.addWidget(self.cmbAgregarProductoModificar)
        self.sbCantidadProductoModificar = QtWidgets.QSpinBox(parent=self.tbModificar)
        self.sbCantidadProductoModificar.setObjectName("sbCantidadProductoModificar")
        self.horizontalLayout_3.addWidget(self.sbCantidadProductoModificar)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 14, 0, 1, 1)
        self.lblEliminarProductoModificar = QtWidgets.QLabel(parent=self.tbModificar)
        self.lblEliminarProductoModificar.setObjectName("lblEliminarProductoModificar")
        self.gridLayout_4.addWidget(self.lblEliminarProductoModificar, 16, 0, 1, 1)
        self.cmbNumeroReservaModificar = QtWidgets.QComboBox(parent=self.tbModificar)
        self.cmbNumeroReservaModificar.setObjectName("cmbNumeroReservaModificar")
        self.gridLayout_4.addWidget(self.cmbNumeroReservaModificar, 1, 0, 1, 1)
        self.lblFechaModificar = QtWidgets.QLabel(parent=self.tbModificar)
        self.lblFechaModificar.setObjectName("lblFechaModificar")
        self.gridLayout_4.addWidget(self.lblFechaModificar, 2, 0, 1, 1)
        self.btnGuardarCambios = QtWidgets.QPushButton(parent=self.tbModificar)
        self.btnGuardarCambios.setObjectName("btnGuardarCambios")
        self.gridLayout_4.addWidget(self.btnGuardarCambios, 19, 0, 1, 1)
        self.lblNumeroReservaModificar = QtWidgets.QLabel(parent=self.tbModificar)
        self.lblNumeroReservaModificar.setObjectName("lblNumeroReservaModificar")
        self.gridLayout_4.addWidget(self.lblNumeroReservaModificar, 0, 0, 1, 1)
        self.dtpFechaModificar = QtWidgets.QCalendarWidget(parent=self.tbModificar)
        self.dtpFechaModificar.setStyleSheet("QCalendarWidget QToolButton {\n"
"    color: black;\n"
"    background-color: #e6e6e6;\n"
"    border: none;\n"
"    margin: 5px;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QCalendarWidget QWidget#qt_calendar_navigationbar {\n"
"    background-color: #e6e6e6;\n"
"}\n"
"\n"
"QCalendarWidget QTableView {\n"
"    selection-background-color: #e6e6e6;\n"
"}\n"
"\n"
"\n"
"QCalendarWidget QMenu::item:selected {\n"
"    background-color: #e6e6e6; /* Color de fondo de la selección */\n"
"}")
        self.dtpFechaModificar.setObjectName("dtpFechaModificar")
        self.gridLayout_4.addWidget(self.dtpFechaModificar, 4, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.cmbTurnoModificar = QtWidgets.QComboBox(parent=self.tbModificar)
        self.cmbTurnoModificar.setObjectName("cmbTurnoModificar")
        self.gridLayout_7.addWidget(self.cmbTurnoModificar, 1, 0, 1, 1)
        self.lblTurnoModificar = QtWidgets.QLabel(parent=self.tbModificar)
        self.lblTurnoModificar.setObjectName("lblTurnoModificar")
        self.gridLayout_7.addWidget(self.lblTurnoModificar, 0, 0, 1, 1)
        self.sbNumeroComensalesModificar = QtWidgets.QSpinBox(parent=self.tbModificar)
        self.sbNumeroComensalesModificar.setObjectName("sbNumeroComensalesModificar")
        self.gridLayout_7.addWidget(self.sbNumeroComensalesModificar, 1, 1, 1, 1)
        self.lblNumeroComensalesModificar = QtWidgets.QLabel(parent=self.tbModificar)
        self.lblNumeroComensalesModificar.setObjectName("lblNumeroComensalesModificar")
        self.gridLayout_7.addWidget(self.lblNumeroComensalesModificar, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_7, 6, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_4.addItem(spacerItem2, 5, 0, 1, 1)
        self.tbReserva.addTab(self.tbModificar, "")
        self.tbEliminar = QtWidgets.QWidget()
        self.tbEliminar.setObjectName("tbEliminar")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tbEliminar)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lblNumeroReservaEliminar = QtWidgets.QLabel(parent=self.tbEliminar)
        self.lblNumeroReservaEliminar.setObjectName("lblNumeroReservaEliminar")
        self.gridLayout_5.addWidget(self.lblNumeroReservaEliminar, 0, 0, 1, 1)
        self.cmbNumeroReservaEliminar = QtWidgets.QComboBox(parent=self.tbEliminar)
        self.cmbNumeroReservaEliminar.setObjectName("cmbNumeroReservaEliminar")
        self.gridLayout_5.addWidget(self.cmbNumeroReservaEliminar, 1, 0, 1, 1)
        self.btnEliminarReserva = QtWidgets.QPushButton(parent=self.tbEliminar)
        self.btnEliminarReserva.setObjectName("btnEliminarReserva")
        self.gridLayout_5.addWidget(self.btnEliminarReserva, 3, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_5.addItem(spacerItem3, 2, 0, 1, 1)
        self.tbReserva.addTab(self.tbEliminar, "")
        self.tbListar = QtWidgets.QWidget()
        self.tbListar.setObjectName("tbListar")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tbListar)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.jgdReservas = QtWidgets.QTableWidget(parent=self.tbListar)
        self.jgdReservas.setObjectName("jgdReservas")
        self.jgdReservas.setColumnCount(0)
        self.jgdReservas.setRowCount(0)
        self.jgdReservas.horizontalHeader().setCascadingSectionResizes(True)
        self.jgdReservas.horizontalHeader().setDefaultSectionSize(400)
        self.jgdReservas.horizontalHeader().setMinimumSectionSize(100)
        self.jgdReservas.verticalHeader().setCascadingSectionResizes(True)
        self.gridLayout_6.addWidget(self.jgdReservas, 0, 0, 1, 1)
        self.tbReserva.addTab(self.tbListar, "")
        self.gridLayout.addWidget(self.tbReserva, 1, 0, 1, 1)

        self.retranslateUi(Ui_Reserva)
        self.tbReserva.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Ui_Reserva)
        Ui_Reserva.setTabOrder(self.tbReserva, self.dtpFechaIngresar)
        Ui_Reserva.setTabOrder(self.dtpFechaIngresar, self.cmbAgregarProductosIngresar)
        Ui_Reserva.setTabOrder(self.cmbAgregarProductosIngresar, self.sbCantidadProductoIngresar)
        Ui_Reserva.setTabOrder(self.sbCantidadProductoIngresar, self.btnAgregarProductoIngresar)
        Ui_Reserva.setTabOrder(self.btnAgregarProductoIngresar, self.cmbPedidoIngresar)
        Ui_Reserva.setTabOrder(self.cmbPedidoIngresar, self.sbCantidadPedidoIngresar)
        Ui_Reserva.setTabOrder(self.sbCantidadPedidoIngresar, self.btnGuardarCambiosPedidoIngresar)
        Ui_Reserva.setTabOrder(self.btnGuardarCambiosPedidoIngresar, self.btnEliminarPedidoIngresar)
        Ui_Reserva.setTabOrder(self.btnEliminarPedidoIngresar, self.btnReservar)
        Ui_Reserva.setTabOrder(self.btnReservar, self.cmbNumeroReservaModificar)
        Ui_Reserva.setTabOrder(self.cmbNumeroReservaModificar, self.dtpFechaModificar)
        Ui_Reserva.setTabOrder(self.dtpFechaModificar, self.cmbAgregarProductoModificar)
        Ui_Reserva.setTabOrder(self.cmbAgregarProductoModificar, self.sbCantidadProductoModificar)
        Ui_Reserva.setTabOrder(self.sbCantidadProductoModificar, self.btnAgregarProductoModificar)
        Ui_Reserva.setTabOrder(self.btnAgregarProductoModificar, self.cmbPedidoModificar)
        Ui_Reserva.setTabOrder(self.cmbPedidoModificar, self.sbCantidadPedidoModificar)
        Ui_Reserva.setTabOrder(self.sbCantidadPedidoModificar, self.btnGuardarCambiosPedidoModificar)
        Ui_Reserva.setTabOrder(self.btnGuardarCambiosPedidoModificar, self.btnEliminarPedidoModificar)
        Ui_Reserva.setTabOrder(self.btnEliminarPedidoModificar, self.btnGuardarCambios)
        Ui_Reserva.setTabOrder(self.btnGuardarCambios, self.cmbNumeroReservaEliminar)
        Ui_Reserva.setTabOrder(self.cmbNumeroReservaEliminar, self.btnEliminarReserva)
        Ui_Reserva.setTabOrder(self.btnEliminarReserva, self.jgdReservas)

    def retranslateUi(self, Ui_Reserva):
        _translate = QtCore.QCoreApplication.translate
        Ui_Reserva.setWindowTitle(_translate("Ui_Reserva", "Reserva"))
        self.btnGuardarCambiosPedidoIngresar.setText(_translate("Ui_Reserva", "Guardar cambios"))
        self.btnEliminarPedidoIngresar.setText(_translate("Ui_Reserva", "Eliminar"))
        self.lblTurnoIngresar.setText(_translate("Ui_Reserva", "Seleccione turno"))
        self.lblNumeroReservaIngresar.setText(_translate("Ui_Reserva", "Número reserva"))
        self.lblNumeroComensalesIngresar.setText(_translate("Ui_Reserva", "Número comensales"))
        self.btnAgregarProductoIngresar.setText(_translate("Ui_Reserva", "Agregar"))
        self.btnReservar.setText(_translate("Ui_Reserva", "Reservar"))
        self.lblEliminarPedidoIngresar.setText(_translate("Ui_Reserva", "Pedido"))
        self.lblFechaIngresar.setText(_translate("Ui_Reserva", "Seleccione fecha"))
        self.lblAgregarProductoIngresar.setText(_translate("Ui_Reserva", "Agregar producto y cantidad a pedido"))
        self.tbReserva.setTabText(self.tbReserva.indexOf(self.tbIngresar), _translate("Ui_Reserva", "Ingresar"))
        self.btnAgregarProductoModificar.setText(_translate("Ui_Reserva", "Agregar"))
        self.btnGuardarCambiosPedidoModificar.setText(_translate("Ui_Reserva", "Guardar cambios"))
        self.btnEliminarPedidoModificar.setText(_translate("Ui_Reserva", "Eliminar"))
        self.lblAgregarProductoModificar.setText(_translate("Ui_Reserva", "Agregar producto y cantidad a pedido"))
        self.lblEliminarProductoModificar.setText(_translate("Ui_Reserva", "Pedido"))
        self.lblFechaModificar.setText(_translate("Ui_Reserva", "Seleccione fecha"))
        self.btnGuardarCambios.setText(_translate("Ui_Reserva", "Guardar cambios"))
        self.lblNumeroReservaModificar.setText(_translate("Ui_Reserva", "Seleccione reserva"))
        self.lblTurnoModificar.setText(_translate("Ui_Reserva", "Seleccione turno"))
        self.lblNumeroComensalesModificar.setText(_translate("Ui_Reserva", "Número comensales"))
        self.tbReserva.setTabText(self.tbReserva.indexOf(self.tbModificar), _translate("Ui_Reserva", "Modificar"))
        self.lblNumeroReservaEliminar.setText(_translate("Ui_Reserva", "Seleccione reserva"))
        self.btnEliminarReserva.setText(_translate("Ui_Reserva", "Eliminar"))
        self.tbReserva.setTabText(self.tbReserva.indexOf(self.tbEliminar), _translate("Ui_Reserva", "Eliminar"))
        self.tbReserva.setTabText(self.tbReserva.indexOf(self.tbListar), _translate("Ui_Reserva", "Listar"))
