# Form implementation generated from reading ui file 'Ui_Reportes.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Reportes(object):
    def setupUi(self, Ui_Reportes):
        Ui_Reportes.setObjectName("Ui_Reportes")
        Ui_Reportes.resize(1366, 768)
        Ui_Reportes.setMinimumSize(QtCore.QSize(800, 600))
        Ui_Reportes.setMaximumSize(QtCore.QSize(1366, 768))
        Ui_Reportes.setStyleSheet("QWidget{\n"
"background-color:white;\n"
"}\n"
"\n"
"QLabel{\n"
"font-family:\"Sans-serif\";\n"
"font-size:14px;\n"
"padding:5px;\n"
"\n"
"}\n"
"\n"
"QDoubleSpinBox{\n"
"font-family:\"Sans-serif\";\n"
"font-size:14px;\n"
"padding:10px 10px;\n"
"border-radius:10px;\n"
"border:2px solid rgb(228, 232, 235);\n"
"}\n"
"\n"
"QComboBox{\n"
"font-family:\"Sans-serif\";\n"
"font-size:14px;\n"
"padding:10px 10px;\n"
"border-radius:10px;\n"
"border:2px solid rgb(228, 232, 235);\n"
"}\n"
"\n"
"QLineEdit{\n"
"font-family:\"Sans-serif\";\n"
"font-size:14px;\n"
"padding:10px 10px;\n"
"border-radius:10px;\n"
"border:2px solid rgb(228, 232, 235);\n"
"}\n"
"\n"
"QPushButton{\n"
"font-family:\"Sans-serif\";\n"
"background-color: #E4E8EB;\n"
"padding: 10px 10px;\n"
"border-radius: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit:hover{\n"
"border:2px solid black;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border:2px solid black;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Ui_Reportes)
        self.gridLayout.setObjectName("gridLayout")
        self.cmbMesInicio = QtWidgets.QComboBox(parent=Ui_Reportes)
        self.cmbMesInicio.setObjectName("cmbMesInicio")
        self.gridLayout.addWidget(self.cmbMesInicio, 1, 0, 1, 1)
        self.cmbAnoInicio = QtWidgets.QComboBox(parent=Ui_Reportes)
        self.cmbAnoInicio.setObjectName("cmbAnoInicio")
        self.gridLayout.addWidget(self.cmbAnoInicio, 1, 1, 1, 1)
        self.lblMesInicio = QtWidgets.QLabel(parent=Ui_Reportes)
        self.lblMesInicio.setObjectName("lblMesInicio")
        self.gridLayout.addWidget(self.lblMesInicio, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.btnObtenerReporte = QtWidgets.QPushButton(parent=Ui_Reportes)
        self.btnObtenerReporte.setObjectName("btnObtenerReporte")
        self.gridLayout.addWidget(self.btnObtenerReporte, 5, 0, 1, 2)
        self.lblAnoInicio = QtWidgets.QLabel(parent=Ui_Reportes)
        self.lblAnoInicio.setObjectName("lblAnoInicio")
        self.gridLayout.addWidget(self.lblAnoInicio, 0, 1, 1, 1)
        self.lblMesFin = QtWidgets.QLabel(parent=Ui_Reportes)
        self.lblMesFin.setObjectName("lblMesFin")
        self.gridLayout.addWidget(self.lblMesFin, 2, 0, 1, 1)
        self.lblAnoFin = QtWidgets.QLabel(parent=Ui_Reportes)
        self.lblAnoFin.setObjectName("lblAnoFin")
        self.gridLayout.addWidget(self.lblAnoFin, 2, 1, 1, 1)
        self.cmbMesfin = QtWidgets.QComboBox(parent=Ui_Reportes)
        self.cmbMesfin.setObjectName("cmbMesfin")
        self.gridLayout.addWidget(self.cmbMesfin, 3, 0, 1, 1)
        self.cmbAnoFin = QtWidgets.QComboBox(parent=Ui_Reportes)
        self.cmbAnoFin.setObjectName("cmbAnoFin")
        self.gridLayout.addWidget(self.cmbAnoFin, 3, 1, 1, 1)
        self.jgdReportes = QtWidgets.QTableWidget(parent=Ui_Reportes)
        self.jgdReportes.setMinimumSize(QtCore.QSize(600, 700))
        self.jgdReportes.setMaximumSize(QtCore.QSize(600, 700))
        self.jgdReportes.setObjectName("jgdReportes")
        self.jgdReportes.setColumnCount(0)
        self.jgdReportes.setRowCount(0)
        self.jgdReportes.horizontalHeader().setCascadingSectionResizes(True)
        self.jgdReportes.horizontalHeader().setDefaultSectionSize(300)
        self.jgdReportes.verticalHeader().setCascadingSectionResizes(True)
        self.gridLayout.addWidget(self.jgdReportes, 1, 2, 4, 1)
        self.lblReportes = QtWidgets.QLabel(parent=Ui_Reportes)
        self.lblReportes.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblReportes.setObjectName("lblReportes")
        self.gridLayout.addWidget(self.lblReportes, 0, 2, 1, 1)

        self.retranslateUi(Ui_Reportes)
        QtCore.QMetaObject.connectSlotsByName(Ui_Reportes)

    def retranslateUi(self, Ui_Reportes):
        _translate = QtCore.QCoreApplication.translate
        Ui_Reportes.setWindowTitle(_translate("Ui_Reportes", "Reportes"))
        self.lblMesInicio.setText(_translate("Ui_Reportes", "Seleccione mes inicio"))
        self.btnObtenerReporte.setText(_translate("Ui_Reportes", "Obtener reporte"))
        self.lblAnoInicio.setText(_translate("Ui_Reportes", "Seleccione año inicio"))
        self.lblMesFin.setText(_translate("Ui_Reportes", "Seleccione mes fin"))
        self.lblAnoFin.setText(_translate("Ui_Reportes", "Seleccione año fin"))
        self.lblReportes.setText(_translate("Ui_Reportes", "Reportes"))
